name: Test
on:
  workflow_dispatch: #true

  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  include-publish: ${{ github.event_name != 'pull_request' && github.ref_name == 'main' }}
  OTHER_PUBLISH: ${{ github.event_name != 'pull_request' && github.ref_name == 'main' }}
  TEST_FALSE: ${{ github.event_name == 'pull_request' }}

jobs:
  Execute:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          printenv
      - name: Test FALSE
        if: ${{ env.TEST_FALSE == 'true' }}
        run: |
          echo "RAN FALSE"
      - name: Test 1
        if: ${{ env.include-publish == 'true' }}
        run: |
          echo "RAN 1"
      - name: Test 2
        if: ${{ env.OTHER_PUBLISH == 'true' }}
        run: |
          echo "RAN 2"
      - name: Test 3
        if: ${{ env['include-publish'] == 'true' }}
        run: |
          echo "RAN 3"